//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LANShutdowner_Client {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings_Viewer : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_Viewer defaultInstance = ((Settings_Viewer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_Viewer())));
        
        public static Settings_Viewer Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4478")]
        public int Setting_port {
            get {
                return ((int)(this["Setting_port"]));
            }
            set {
                this["Setting_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Лаборатория №3")]
        public string Setting_group_name2 {
            get {
                return ((string)(this["Setting_group_name2"]));
            }
            set {
                this["Setting_group_name2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Лаборатория №2")]
        public string Setting_group_name3 {
            get {
                return ((string)(this["Setting_group_name3"]));
            }
            set {
                this["Setting_group_name3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Лаборатория №1")]
        public string Setting_group_name4 {
            get {
                return ((string)(this["Setting_group_name4"]));
            }
            set {
                this["Setting_group_name4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Аудитория 13")]
        public string Setting_group_name5 {
            get {
                return ((string)(this["Setting_group_name5"]));
            }
            set {
                this["Setting_group_name5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Админская")]
        public string Setting_group_name1 {
            get {
                return ((string)(this["Setting_group_name1"]));
            }
            set {
                this["Setting_group_name1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128.128.14.101")]
        public string Setting_gr1_ipbegin {
            get {
                return ((string)(this["Setting_gr1_ipbegin"]));
            }
            set {
                this["Setting_gr1_ipbegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128.128.14.1")]
        public string Setting_gr2_ipbegin {
            get {
                return ((string)(this["Setting_gr2_ipbegin"]));
            }
            set {
                this["Setting_gr2_ipbegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0.0.0")]
        public string Setting_gr3_ipbegin {
            get {
                return ((string)(this["Setting_gr3_ipbegin"]));
            }
            set {
                this["Setting_gr3_ipbegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0.0.0")]
        public string Setting_gr4_ipbegin {
            get {
                return ((string)(this["Setting_gr4_ipbegin"]));
            }
            set {
                this["Setting_gr4_ipbegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0.0.0")]
        public string Setting_gr5_ipbegin {
            get {
                return ((string)(this["Setting_gr5_ipbegin"]));
            }
            set {
                this["Setting_gr5_ipbegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128.128.14.103")]
        public string Setting_gr1_ipend {
            get {
                return ((string)(this["Setting_gr1_ipend"]));
            }
            set {
                this["Setting_gr1_ipend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128.128.14.10")]
        public string Setting_gr2_ipend {
            get {
                return ((string)(this["Setting_gr2_ipend"]));
            }
            set {
                this["Setting_gr2_ipend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255.255.255.255")]
        public string Setting_gr3_ipend {
            get {
                return ((string)(this["Setting_gr3_ipend"]));
            }
            set {
                this["Setting_gr3_ipend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255.255.255.255")]
        public string Setting_gr4_ipend {
            get {
                return ((string)(this["Setting_gr4_ipend"]));
            }
            set {
                this["Setting_gr4_ipend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255.255.255.255")]
        public string Setting_gr5_ipend {
            get {
                return ((string)(this["Setting_gr5_ipend"]));
            }
            set {
                this["Setting_gr5_ipend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string Setting_ip_list {
            get {
                return ((string)(this["Setting_ip_list"]));
            }
            set {
                this["Setting_ip_list"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_CheckBox_AutoStart {
            get {
                return ((bool)(this["Setting_CheckBox_AutoStart"]));
            }
            set {
                this["Setting_CheckBox_AutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_CheckBox_AutoScan {
            get {
                return ((bool)(this["Setting_CheckBox_AutoScan"]));
            }
            set {
                this["Setting_CheckBox_AutoScan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setting_TimeAutoScan {
            get {
                return ((int)(this["Setting_TimeAutoScan"]));
            }
            set {
                this["Setting_TimeAutoScan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_CheckBox_ScanAppStart {
            get {
                return ((bool)(this["Setting_CheckBox_ScanAppStart"]));
            }
            set {
                this["Setting_CheckBox_ScanAppStart"] = value;
            }
        }
    }
}
